name: My First Workflow

# Event 
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - closed
    branches:
      - 'main'
      - 'dev-**'
      - 'releases/**'
  push:
    branches:
      - 'main'
      - 'dev-**'
      - 'releases/**'

  workflow_dispatch:

# Workflow
jobs:
    test:
        runs-on: ubuntu-latest
        # step
        steps:
           - name: checkout code
             uses: actions/checkout@v4

           - name: Set up Node.js
             uses: actions/setup-node@v4
             with:
              node-version: "18"

           - name: cache of modules
             uses: actions/cache@v4
             with:
              path: node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
               ${{ runner.os }}-node-
          
           - name: install dependencies
             run: npm install
             
           - name: npm test
             id: test-report
             run: npm test
          
           - name: workflow condetion
             if: failure() && steps.test-report.outcome == 'failure'
             uses: actions/upload-artifact@v4
             with:
              name: dist-files
              path: ./public


          

    build:
      needs: test
      runs-on: ubuntu-latest
      steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: "18"
          
          - name: cache of modules
            uses: actions/cache@v4
            with:
              path: node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
               ${{ runner.os }}-node-

          - name: install dependencies
            run: npm install

          - name: Build Project
            run: npm run build
          
          - name: upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: dist-files
              path: ./public
          
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
         - name: checkout code
           uses: actions/checkout@v4

         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
            node-version: "18"
         
         - name: cache of modules
           uses: actions/cache@v4
           with:
              path: node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
               ${{ runner.os }}-node-

         - name: install dependencies
           run: npm install

         - name: download artifacts
           uses: actions/download-artifact@v4
           with:
            name: dist-files

         - name: output contents
           run: ls


         - name: deploy Application
           run: echo "Deploying...."

        
        #  - name: Deploy to GitHub Pages
        #    uses: peaceiris/actions-gh-pages@v4
        #    with:
        #     github_token: ${{ secrets.ACTION_TOKEN }}
        #     publish_dir: ./build

          