name: My First Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

            - uses: actions/checkout/v4

            - name: Run a one-line script
              run:  echo Hello, world!

            - name: Run multiple commands
              run: |
                echo "this is first command"
                echo "this is second command"